#pragma once

#include "particlepm/includes.hpp"
#include "particlepm/declarations.hpp"
#include "particlepm/version.hpp"
#include "particlepm/selector.hpp"
#include "particlepm/license.hpp"
#include "particlepm/dependency.hpp"
#include "particlepm/github.hpp"
#include "particlepm/gitrepo.hpp"
#include "particlepm/pkgconfig.hpp"
#include "particlepm/package.hpp"
#include "particlepm/target.hpp"
#include "particlepm/file.hpp"
#include "particlepm/utils.hpp"
